name: personapi

services:
  personapi_web:
    container_name: personapi_web
    build:
      context: .
      dockerfile: personapi-dotnet/Dockerfile
    ports:
      - "5233:8080"
    depends_on:
      - sql_server
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql_server,1433;Database=persona_db;User Id=sa;Password=Password123;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: Development

  sql_server:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Password123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password123 -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  sql_server.configurator:
    container_name: configurator
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    depends_on:
      sql_server:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S sql_server -U sa -P Password123 -d master -C -i docker-entrypoint-initdb.d/init.sql;
      /opt/mssql-tools18/bin/sqlcmd -S sql_server -U sa -P Password123 -d master -C -i docker-entrypoint-initdb.d/example.sql;
      echo "All done!";
      '

volumes:
  mssql_data:

